allowBuilds:
  '@firebase/util': set this to true or false
  '@nestjs/core': true
  '@scarf/scarf': true
  bcrypt: false
  better-sqlite3: false
  protobufjs: set this to true or false
  sqlite3: false
