packages:
  - '.'

allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  '@nestjs/core': true
  '@scarf/scarf': true
  '@swc/core': true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
